CplexConnect/CplexConnect/Models/ScheduleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CplexConnect.Models
{
    public class ScheduleViewModel
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public virtual List<Section> SectionList { get; set; }
        public virtual List<Instructor> InstructorList { get; set; }
        public virtual List<InputData> ModelToList { get; set; }
        public virtual List<Tuple<int,int>> CourseAndInstr {get; set;}
        public List<Tuple<Section,Instructor>> CombinedList { get; set; }
        public virtual int SemesterNumber { get; set; }

    }
}

CplexConnect/CplexConnect/Controllers/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CplexConnect.Models;
using OfficeOpenXml;
using ClosedXML.Excel;
using System.Web.UI.WebControls;
using System.IO;
using MoreLinq;

namespace CplexConnect.Controllers
{

    public class ScheduleController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Schedule
        public ActionResult Index(string sortBy, string sortBySemester)
        {
            ScheduleViewModel scheduleViewModel = new ScheduleViewModel();
            //so sortbysemester goes to the current verison
            scheduleViewModel.SemesterNumber = 0;
            //checks if dropdown is triggered through jQuery
            if (sortBySemester != null)
            {
                scheduleViewModel.SemesterNumber = int.Parse(sortBySemester);
            }
            else
            {
                sortBySemester = "0";
            }


            //Tuple of View model and Input Data
            var tuple = new Tuple<ScheduleViewModel, InputData>(new ScheduleViewModel(), new InputData());
            //allowing user to sort courses by program
            List<Section> sectionList = db.Sections.ToList();
            List<Instructor> instructList = db.Instructors.OrderBy(a => a.FirstName).ToList();

            if (sortBy == "OM")
            {
                tuple.Item1.SectionList = sectionList.Where(s => s.Program == "OM").ToList();
            }
            else if (sortBy == "MIS")
            {
                tuple.Item1.SectionList = sectionList.Where(s => s.Program == "MIS").ToList();
            }
            else if (sortBy == "ST")
            {
                tuple.Item1.SectionList = sectionList.Where(s => s.Program == "ST").ToList();
            }
            else
            {
                sortBy = "All";
                tuple.Item1.SectionList = sectionList;
            }


            //semster sort that checks if everything is distinct for the semester ID we are looking for and then creates a dropdown from all of those
            var semDb = db.InputData.DistinctBy(x => x.Semester_Id).Distinct().ToList();
            List<SelectListItem> items = new List<SelectListItem>();
            foreach (var a in semDb)
            {
                if (a.SemesterName == null)
                {
                    items.Add(new SelectListItem() { Text = "Current", Value = a.Semester_Id.ToString() });
                }
                else
                    items.Add(new SelectListItem() { Text = a.SemesterName, Value = a.Semester_Id.ToString() });
            }

            //sort everything
            string sortByStart = sortBy.Substring(0, 1);
            string sortByEnd = sortBy.Substring(1, sortBy.Length - 1);

            ViewBag.SortTheSems = items;
            // Viewbags back to the View
            ViewBag.SortBySemester = sortBySemester;
            ViewBag.SortBy = sortByStart.ToUpper() + sortByEnd;

            //TempData to go to post if needed
            tuple.Item1.ModelToList = db.InputData.ToList();
            tuple.Item1.InstructorList = instructList;
            TempData["sortBy"] = sortBy;
            TempData["sortBySemester"] = sortBySemester;
            return View(tuple);
        }



        [HttpPost]
        public ActionResult Index(ScheduleViewModel scheduleViewModel, FormCollection form, string sortBy, string sortBySemester)
        {
            //Tempdata
            sortBy = TempData["sortBy"].ToString();
            sortBySemester = TempData["sortBySemester"].ToString();
            // finds number from tempdata
            scheduleViewModel.SemesterNumber = int.Parse(sortBySemester);
            //creates list of everything
            List<Section> sectionList = db.Sections.ToList();
            List<Instructor> instructList = db.Instructors.OrderBy(a => a.FirstName).ToList();
            List<Tuple<Section, Instructor>> combinedList = new List<Tuple<Section, Instructor>>();
            scheduleViewModel.CombinedList = combinedList;
            //creates ability to sort by program
            if (sortBy == "OM")
            {
                scheduleViewModel.SectionList = sectionList.Where(s => s.Program == "OM").ToList();
            }
            else if (sortBy == "MIS")
            {
                scheduleViewModel.SectionList = sectionList.Where(s => s.Program == "MIS").ToList();
            }
            else if (sortBy == "ST")
            {
                scheduleViewModel.SectionList = sectionList.Where(s => s.Program == "ST").ToList();
            }
            else
            {
                sortBy = "All";
                scheduleViewModel.SectionList = sectionList;
            }


            scheduleViewModel.InstructorList = instructList;
            //List of inputdata
            List<InputData> inList = new List<InputData>();
            //List of strings of info from inList
            List<string> test = new List<string>();
            var counter = scheduleViewModel.SectionList.Count();
            for (int i = 1; i <= counter; i++)
            {
                //checking and getting each radio button
                var name = "radioCol" + i;
                name = form[name];
                if (name != null)
                {
                    //adding to the tuple
                    test.Add(name);
                    var tempName = int.Parse(name);
                    var newTup = new Tuple<Section, Instructor>(scheduleViewModel.SectionList.Where(s => s.ID == i).FirstOrDefault(), scheduleViewModel.InstructorList.Where(k => k.ID == tempName).FirstOrDefault());
                    combinedList.Add(newTup);
                }
                //Break when Null
                else
                    break;
            }


            scheduleViewModel.CombinedList = combinedList;
            //find everyclassID and add it to the list
            List<int> classIdList = db.InputData.Select(a => a.Course_Id).ToList();
            var inputList = db.InputData.ToList();
            //Iterate through combined list that is added from enough
            foreach (var a in combinedList)
            {
                InputData input = new InputData();
                input.Course_Id = a.Item1.ID;
                input.Instructor_Id = a.Item2.ID;
                input.CourseName = a.Item1.Course;
                //checks if list is null
                if (inputList.Count == 0)
                {
                    db.InputData.Add(input);
                    db.SaveChanges();

                }
                else
                {
                    //checks if the course has not already been added
                    if (!classIdList.Contains(input.Course_Id))
                    {
                        db.InputData.Add(input);
                        db.SaveChanges();
                    }
                    else
                    {
                        //checks if the course has not already been added
                        var removeItem = db.InputData.Where(c => c.Course_Id == input.Course_Id).FirstOrDefault();
                        input.Semester_Id = removeItem.Semester_Id;
                        db.InputData.Remove(removeItem);
                        db.InputData.Add(input);
                        db.SaveChanges();
                    }
                }
            }


            var inputListPost = db.InputData.ToList();
            var tList = db.Instructors.ToList();


            foreach (var t in tList)
            {
                var temp = inputListPost.Where(a => a.Instructor_Id == t.ID).ToList();
                t.AssignCourseLoad = temp.Count();
                db.SaveChanges();

            }
            //db.Schedules.Add(scheduleViewModel);
            return View("SaveIndex", scheduleViewModel);
        }
        [Authorize(Roles = "admin")]
        public ActionResult Export()
        { 

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult Export(FormCollection form)
        {
            //Creates a new semester. formcollection
            var name = form["SemesterName"];
            int counter = 0;
            //find the largest semester 
            var counterFinder = db.InputData.OrderByDescending(s => s.Semester_Id).First();
            counter = counterFinder.Semester_Id;
            //adds 
            counter++;
            InputData input = new InputData();
            List<InputData> inputList = db.InputData.ToList();

            foreach (var i in inputList)
            {
                //Change the name and Id if it is zero which is the current save
                var semChange = db.InputData.Where(x => x.Semester_Id == 0).ToList();
                foreach (var s in semChange)
                {
                    s.Semester_Id = counter;
                    s.SemesterName = name;
                    db.SaveChanges();

                }
            }

            //reset assigned course load
            var assignedReset = db.Instructors.ToList();
            foreach(var r in assignedReset)
            {
                r.AssignCourseLoad = 0;
                db.SaveChanges();
            }


            return View("../Home/Index");
            //var sections = new System.Data.DataTable("Sections");
            //sections.Columns.Add("Program", typeof(string));
            //sections.Columns.Add("Course ID", typeof(string));
            //sections.Columns.Add("Instructor", typeof(string));
            //sections.Columns.Add("Attribute", typeof(string));
            //sections.Columns.Add("Notes", typeof(string));

            //var allSections = db.Sections.ToList();

            //foreach (Section s in allSections)
            //{

CplexConnect/CplexConnect/Views/Schedule/Export.cshtml
@model CplexConnect.Models.InputData

@{
    ViewBag.Title = "Export";
}

<h2>Export</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>InputData</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SemesterName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SemesterName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SemesterName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CplexConnect/CplexConnect/Views/Schedule/Index.cshtml
@using System.Linq
@using CplexConnect.Models;
@model Tuple<ScheduleViewModel, InputData>
<!--allows user to sort by program-->
<select  id="sortBy" class="form-control pull-right">
    <option value="" disabled selected>@ViewBag.SortBy</option>
    <option value="OM">OM</option>
    <option value="MIS">MIS</option>
    <option value="ST">STATS</option>
</select>
<label class="pull-right">Sort By: </label>


@Html.DropDownList("SortTheSems", null, new { @id = "semBy", @class = "SortSem" })

@*<select id="semBy" class="form-control pull-left">
    <option value="" disabled selected>@ViewBag.SortBySemester</option>
    <option value="0">Current</option>
    <option value="1">Fall</option>
</select>*@
<label class="pull-left" style="margin-left:9em">Sort By: </label>
<!--initializes values for calculating course load and assigned instructors-->
<h2>Input Data</h2>
@{int m = 1;
    int t = 1;
    int d = 0;
    int w = 0;
    var instNum = "0";
    int instrNum = 0;
    List<int> courseNum = new List<int>();
    List<int> InstrNum = new List<int>();
    var temp = ViewBag.SortBySemester;
    foreach (var items in temp)
    {
         instNum = items.ToString();

    }
            instrNum = int.Parse(instNum);
}


@using (Html.BeginForm("Index", "Schedule", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table id="inputData" class="stripe row-border order-column" cellspacing="0">
        <thead>
            <tr>
                <th style="background-color: #808080; color: white;">
                    Instructor
                </th>
                <th style="background-color: #808080;color: white;">
                    Max Course Load
                </th>
                <th style="background-color: #808080;color: white;">
                    Assigned Course Load
                </th>
                @*Razor to foreach through each course and add it*@
                @foreach (var l in Model.Item1.SectionList)
                {
                    foreach (var f in Model.Item1.ModelToList)
                    {
                        //assigns instructor to course
                        if (l.ID == f.Course_Id)
                        {
                            courseNum.Add(m);
                            InstrNum.Add(f.Instructor_Id);
                        }

                    }
                    m++;
                    <th class="line">
                        @l.Course
                    </th>
                }
            </tr>
        </thead>
        <tbody>
            @*Foreach through the instructors*@ 
            @foreach (var i in Model.Item1.InstructorList)
            {
                <tr>
                    <td style="background-color:#808080; color:white;">
                        @i.LastName, @i.FirstName
                    </td>
                    <td style="background-color:#808080; color:white;">
                        @i.MaxCourseLoad
                    </td>
                    <td style="background-color:#808080; color:white;" id="assign">
                        @i.AssignCourseLoad
                    </td>
                    @for (int j = 1; j < m; j++)
                    {
                        var check = false;
                        foreach (var e in Model.Item1.ModelToList)
                        {
                            //checking if the radio button should be checked
                            if (e.Course_Id == j && i.ID == e.Instructor_Id && e.Semester_Id == instrNum)
                            {
                                <td><input type="radio" checked="checked" id="radioCol@(j)" name="radioCol@(j)" value="@(i.ID)" onclick="SumValue(this.value)"></td>
                                check = true;
                                }
                            }
                            if (check != true)
                            {
                            <td><input type="radio" id="radioCol@(j)" name="radioCol@(j)" value="@(i.ID)" onclick="SumValue(this.value)"></td>
                        }
                    }
                </tr>
                d++;

                t++;
            }
        </tbody>
    </table>
            <div class="form-group">
                <input type="submit" value="Submit" />
            </div>
}


<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.15/css/dataTables.jqueryui.min.css" />
<script type="text/javascript" src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.15/js/dataTables.jqueryui.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/fixedcolumns/3.2.1/js/dataTables.fixedColumns.min.js"></script>
<script type="text/javascript">

    //Jquery for dropdown
    $(document).ready(function () {
        $('#sortBy').change(function () {

            if ($(this).val() != "") {

                window.location.href = "http://" + window.location.host + window.location.pathname + "?sortBy=" + $(this).val();
            }
        });
    });

    //Jquery for dropdown
    $(document).ready(function () {
        $('#semBy').change(function () {

            if ($(this).val() != "") {

                window.location.href = "http://" + window.location.host + window.location.pathname + "?SortBySemester=" + $(this).val();
            }
        });
    });

    //jQuery for the Datatables
    $(document).ready(function () {
        $('#inputData').DataTable({
            "scrollY": "50vh",
            "scrollX": true,
            scrollCollapse: true,
            paging: false,
            fixedColumns: {
                leftColumns: 3
            },
            language: {
                searchPlaceholder: "Search Instructor"
            }

        });
        $(window).resize(setWidthOfContainer);
        function setWidthOfContainer() {
            $('div.container').css('width', '90%');

        }
        setWidthOfContainer();

    });






    //function SumValue(btn) {
    //    var temp = document.getElementById("assign").innerHTML.trimmed();
    //    var Assigned = parseInt(temp);
    //    var btnVal = parseInt(btn);
    //    var total = (Assigned + btnVal);
    //    document.getElementById("assign").innerHTML = total;
        //alert(total);
    //}


    String.prototype.trimmed = function () {
        return this.replace(
            /^(\s|&nbsp;|<br\s*\/?>)+?|(\s|&nbsp;|<br\s*\/?>)+?$/ig, ' '
        ).trim();
    }
</script>

CplexConnect/CplexConnect/Views/Schedule/SaveIndex.cshtml
@model CplexConnect.Models.ScheduleViewModel
@{
    ViewBag.Title = "SaveIndex";
}

<html>
<body>
    <h2>SaveIndex</h2>
    <div>
        @{
            var check = -1;
            foreach (var i in Model.CombinedList)
            {

                if (check != i.Item2.ID)
                {
                @(i.Item2.FirstName + " " + i.Item2.LastName + "  --  ")

                    var courses = Model.CombinedList.Where(a => a.Item2.ID == i.Item2.ID).ToList();
                    foreach (var c in courses)
                    {
                    @(c.Item1.Course + ",")
                    }
                <br />
                    }
                check = i.Item2.ID;
                }

            }


    </div>
</body>
</html>